### ISSUE TITLE
change prefix in a template

### ISSUE THREAD

**Issue by funkyfuture** [fdiehr/entermuseum4punkt0#3]
moved from https://github.com/funkyfuture/m4p0-rs-metadata-import/issues/10#issuecomment-575171929

> Franzi muss das Prefix ändern bei:
https://researchspace.curving.space/resource/?uri=Template%3Ahttp%3A%2F%2Fwww.ics.forth.gr%2Fisl%2Frdfs%2F3D-COFORM_CRMdig.rdfs%23D1.Digital_Object

**Comment by fdiehr** [comment]
done. template has now the right iri: https://researchspace.curving.space/resource/?uri=Template%3Ahttp%3A%2F%2Fwww.ics.forth.gr%2Fisl%2FCRMdig%2FD1.Digital_Object
